= Kotlin/Ktor Hello World

Kotlin can be used with Spring Boot, it is well supported.
There also is a list of  other framework options for
https://kotlinlang.org/docs/reference/server-overview.html[using Kotlin for Server-side Development]
in the official Kotlin docs.

This is a simple example for Kotlin using https://ktor.io/[Ktor]. I chose it
as I wanted to try something new.

I picked Ktor over some other options as it is really made for idiomatic Kotlin.
There is support for many use cases we typically want in backend development
(JWT authentication, Logging, CORS, Tracing, Metrics, and OpenAPI 3 API-first support).

There is one *big caveat* with Ktor, and that is persistence and integration with JMS or Kafka:
Out of the box, there is no support for JPA/Hibernate. If you agree with the authors of
https://spring.io/projects/spring-data-jdbc[Spring Data JDBC] that JPA is actually too complex
and simpler models actually lead to more maintainable applications, there are https://touk.pl/blog/2019/12/30/announcing-krush[options]
like https://github.com/JetBrains/Exposed[JetBrain's Exposed] or https://github.com/TouK/krush[Krush].

And in a world of https://knative.dev/docs/eventing/[Knative eventing] and
https://camel.apache.org/camel-k/latest/index.html[Apache Camel K]
(https://camel.apache.org/blog/2020/06/camel-k-release-1.0.0/[release blog],
https://developers.redhat.com/devnation/tech-talks/serverless-apps-camelk?sc_cid=7013a000002gj5pAAA[Event-driven serverless applications with Camel K | DevNation Tech Talk]),
maybe direct integration is not even a strict requirement, let's see what the future brings.


== Stop talking, go run It

To see it in action, simply run:

[source,shell script]
----
./gradlew run
----

This will start an embedded web server, listening on port 8080.

* Simple hello world: http://localhost:8080/
* Hello world JSON API: http://localhost:8080/hello-world
* Hello viesure: http://localhost:8080/hello-world?name=viesure
* Another approach: http://localhost:8080/hello/viesure


== Useful Resources

* https://plugins.jetbrains.com/plugin/10823-ktor[Ktor IntelliJ plugin] - The plugin supports generating new
  projects using https://start.ktor.io/, similar to the https://start.ktor.io/[Spring Initializr].
* https://ryanharrison.co.uk/2018/04/14/kotlin-ktor-exposed-starter.html[RESTful Kotlin with Ktor and Exposed]
